flowchart TD
    M___algitex[".algitex<br/>1678 funcs"]
    docker__planfile_mcp["docker.planfile-mcp<br/>10 funcs"]
    examples__01_quickstart["examples.01-quickstart<br/>1 funcs"]
    examples__09_workspace["examples.09-workspace<br/>11 funcs"]
    examples__10_cicd["examples.10-cicd<br/>8 funcs"]
    examples__33_hybrid_autofix["examples.33-hybrid-autofix<br/>10 funcs"]
    src__algitex["src.algitex<br/>685 funcs"]
    src__algitex ==>|53| M___algitex
    docker__planfile_mcp -->|3| M___algitex
    examples__33_hybrid_autofix -->|3| M___algitex
    examples__01_quickstart -->|1| M___algitex
    examples__10_cicd -->|1| M___algitex
    examples__09_workspace -->|1| M___algitex
